spring:
    profiles:
        active: dev
    application:
        name: "Smart Home System"
        version: "1.0"
---
spring:
    config:
        activate:
            on-profile: dev
server:
    port: 8080
logging:
    level:
        com.example.demo: DEBUG
---
spring:
    config:
        activate:
            on-profile: production
server:
    port: 9001
logging:
    level:
        com.example.demo: INFO
---
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/smart_house_db
        username: postgres
        password: Dream2005)
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
smart-home:
    auto-mode: true
    max-power-consumption: 5000.0